server:
  port: 9210
  error:
    include-stacktrace: never

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant_management22?createDatabaseIfNotExist=true
    username: root
    password: 1704Wj@2001

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
      show-sql: true
